### ISSUE TITLE
Enable "TrinityCore settings" by default in tc_recast_demo branch

### ISSUE THREAD

**Issue by jackpoz** [TrinityCore/recastnavigation#1]
Enable "TrinityCore settings" by default in tc_recast_demo branch

**Comment by jackpoz** [comment]
PR opened

**Comment by funjoker** [comment]
![image](https://user-images.githubusercontent.com/846960/160261017-b36a6874-290f-4205-aec9-daafbf3c879b.png)

after 8bd192131d80586bfc3966a8caeddbaf7721eefb it's bugged


6d5b0eda6bc02b6579592d656883001874b7c53d works.

**Comment by jackpoz** [comment]
fixed in https://github.com/TrinityCore/recastnavigation/commit/8655a1b54830d26314ce8c28e1c22ecb2aae031a
